#!/usr/bin/env bash
# Display some info about subdomains

dig_domain() {
    ip=$(dig "$1" | grep -A1 'ANSWER SECTION:' | awk 'NR == 2 {print $5}')
    record=$(dig "$1" | grep -A1 'ANSWER SECTION:' | awk 'NR == 2 {print $4}')
    local values=("$ip" "$record")
    echo "${values[@]}"
}

if [ $# -ge 2 ];
then
    sub="$2.$1"
    #vals=($(dig_domain "$sub"))
    read -ra vals < <(dig_domain "$sub")
    echo "The subdomain $2 is a ${vals[1]} record and points to ${vals[0]}"
else
    sub="www.$1"
    #vals=($(dig_domain "$sub"))
    read -ra vals < <(dig_domain "$sub")
    echo "The subdomain www is a ${vals[1]} record and points to ${vals[0]}"

    sub="lb-01.$1"
    #vals=($(dig_domain "$sub"))
    read -ra vals < <(dig_domain "$sub")
    echo "The subdomain lb-01 is a ${vals[1]} record and points to ${vals[0]}"

    sub="web-01.$1"
    #vals=($(dig_domain "$sub"))
    read -ra vals < <(dig_domain "$sub")
    echo "The subdomain web-01 is a ${vals[1]} record and points to ${vals[0]}"

    sub="web-02.$1"
    #vals=($(dig_domain "$sub"))
    read -ra vals < <(dig_domain "$sub")
    echo "The subdomain web-02 is a ${vals[1]} record and points to ${vals[0]}"
fi
