#!/usr/bin/env bash
# create a smylink of the default available site
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo kill "$(pgrep nginx | head -1)"
