#!/usr/bin/env bash
# change localhost and facebook.com IP resolvers

cp /etc/hosts ~/hosts.tmp
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.tmp
sed -i '$a\8.8.8.8\tfacebook.com' ~/hosts.tmp
cp -f ~/hosts.tmp /etc/hosts
rm ~/hosts.tmp
